[tool.poetry]
name = "vqa-e2e"
version = "0.1.0"
description = ""
authors = ["sam99dave <sam99dave@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
